spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_SCHEMA:dpm_core}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          apple:
            client-id: ${LOCAL_APPLE_CLIENT_ID}
            redirect-uri: ${LOCAL_APPLE_REDIRECT_URI}
  jpa:
    hibernate:
      ddl-auto: validate
server:
  port: 8080
apple:
  client-id: ${LOCAL_APPLE_CLIENT_ID}
  key-id: ${LOCAL_APPLE_KEY_ID}
  team-id: ${LOCAL_APPLE_TEAM_ID}
  private-key: ${LOCAL_APPLE_PRIVATE_KEY}
  redirect-uri: ${LOCAL_APPLE_REDIRECT_URI}