spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://${DEV_DB_HOST:localhost}:${DEV_DB_PORT:3306}/${DEV_DB_SCHEMA:dpm_core}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
           apple:
             client-id: ${DEV_APPLE_CLIENT_ID}
             redirect-uri: ${DEV_APPLE_REDIRECT_URI}

logging:
  level:
    org.springframework.orm.jpa: INFO
apple:
  client-id: ${DEV_APPLE_CLIENT_ID}
  key-id: ${DEV_APPLE_KEY_ID}
  team-id: ${DEV_APPLE_TEAM_ID}
  private-key: ${DEV_APPLE_PRIVATE_KEY}
  redirect-uri: ${DEV_APPLE_REDIRECT_URI}
