name: Deploy to Production Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-22.04

    steps:
      - name: "ë ˆí¬ì§€í† ë¦¬ë¥¼ ì²´í¬ì•„ì›ƒí•œë‹¤."
        uses: actions/checkout@v4

      - name: "Gradle Wrapper ë¬´ê²°ì„±ì„ ê²€ì¦í•œë‹¤."
        uses: gradle/actions/wrapper-validation@v4

      - name: "JDK 21ì„ ì„¤ì •í•œë‹¤."
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
        cache: 'gradle'

      - name: "Kotlin ì†ŒìŠ¤ë¥¼ ì»´íŒŒì¼í•œë‹¤."
        run: ./gradlew compileKotlin --configuration-cache --build-cache

      - name: "Discordë¡œ ë¹Œë“œ ì‹¤íŒ¨ë¥¼ ì•Œë¦°ë‹¤"
        if: failure()
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            âŒ **ì»´íŒŒì¼ ë„ì¤‘ ë¬¸ì œê°€ ë°œìƒí–ˆìŠµë‹ˆë‹¤.**
            branch : `${{ github.head_ref }}`
            pull-request : `${{ github.event.pull_request.title }}`
            [ğŸ”— ì‘ì—… ìš”ì•½ ë³´ê¸°](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})

  deploy:
    needs:
      - compile
    runs-on: ubuntu-22.04
    env:
      SPRING_PROFILES_ACTIVE: prod
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      IMAGE_TAG: prod-${{ github.sha }}

    steps:
      - name: "ë ˆí¬ì§€í† ë¦¬ë¥¼ ì²´í¬ì•„ì›ƒí•œë‹¤."
        uses: actions/checkout@v4

      - name: "JDK 21ì„ ì„¤ì •í•œë‹¤."
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: "Docker buildxë¥¼ ì„¤ì •í•œë‹¤."
        uses: docker/setup-buildx-action@v3

      - name: "Dockerhub ë¡œê·¸ì¸"
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: "Jibì„ ì‚¬ìš©í•˜ì—¬ Docker ì´ë¯¸ì§€ë¥¼ ë¹Œë“œ í›„ Dockerhubì— í‘¸ì‹œí•œë‹¤."
        run: |
          ./gradlew jib \
            -Djib.to.auth.username=${{ env.DOCKER_USERNAME }} \
            -Djib.to.auth.password=${{ env.DOCKER_PASSWORD }} \
            -Djib.to.image=${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPOSITORY }}:${{ env.IMAGE_TAG }} \
            -Djib.to.tags=latest,${{ env.IMAGE_TAG }} \
        env:
          DOCKER_USERNAME: ${{ env.DOCKER_USERNAME }}
          DOCKER_REPOSITORY: ${{ env.DOCKER_REPOSITORY }}
          DOCKER_PASSWORD: ${{ env.DOCKER_PASSWORD }}
          IMAGE_TAG: ${{ env.IMAGE_TAG }}

      - name: "ì„œë²„ì— ë°°í¬í•œë‹¤."
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_SERVER_HOST }}
          username: ${{ secrets.PROD_SERVER_USERNAME }}
          key: ${{ secrets.PROD_SERVER_SSH_KEY }}
          script: |
            docker login -u ${{ env.DOCKER_USERNAME }} -p ${{ env.DOCKER_PASSWORD }}
            docker pull ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPOSITORY }}:${{ env.IMAGE_TAG }}
            docker service update \
              --image ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPOSITORY }}:${{ env.IMAGE_TAG }} \
              --env PROD_DB_HOST=${{ secrets.PROD_DB_HOST }} \
              --env PROD_DB_PORT=${{ secrets.PROD_DB_PORT }} \
              --env PROD_DB_SCHEMA=${{ secrets.PROD_DB_SCHEMA }} \
              --env PROD_DB_USERNAME=${{ secrets.PROD_DB_USERNAME }} \
              --env PROD_DB_PASSWORD=${{ secrets.PROD_DB_PASSWORD }} \
              --detach=true \
              --update-parallelism 1 \
              --update-delay 10s \
              --update-failure-action pause \
              --update-monitor 30s \
              core-service

      - name: "Discordë¡œ Production ë°°í¬ ì‹¤íŒ¨ë¥¼ ì•Œë¦°ë‹¤"
        if: failure()
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            âŒ **`Production` ë°°í¬ ë„ì¤‘ ë¬¸ì œê°€ ë°œìƒí–ˆìŠµë‹ˆë‹¤.**
            branch : `${{ github.head_ref }}`
            pull-request : `${{ github.event.pull_request.title }}`
            [ğŸ”— ì‘ì—… ìš”ì•½ ë³´ê¸°](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
